package jdouglas9025.github.io.greatmoviescollection.model;

//Model class for great-movies-collection app
public class Movie {
    private int id;
    private String title;
    private int revenue;

    //Default Constructor
    public Movie() {
        this.title = "";
        this.revenue = 0;
    }

    //Main constructor (id auto-generated by DB's auto-increment feature)
    public Movie(String title, int revenue) {
        this.title = title;
        this.revenue = revenue;
    }

    //Internal constructor for creating existing Movie object
    public Movie(int id, String title, int revenue) {
        this(title, revenue);

        this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public int getRevenue() {
        return revenue;
    }

    public void setRevenue(int revenue) {
        this.revenue = revenue;
    }
}
